name: Studio Hinge
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Studio Hinge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b100c'
    - '#323e3e'
    - '#ae9a8d'
    - '#d7bea8'
  brandStrength: 0.8125
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
